apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: chatbot-ui-staging
  labels:
    app: chatbot-ui-staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatbot-ui-staging
  template:
    metadata:
      labels:
        app: chatbot-ui-staging
    spec:
      containers:
        - name: chatbot-ui-staging
          image: jiggyai/chatbot-ui:may26
          imagePullPolicy: Always            
          resources: {}
          ports:
            - containerPort: 3000
          env:
            - name: OPENAI_API_HOST
              value: https://api-staging.gpt-gateway.com
            - name: NEXT_PUBLIC_DEFAULT_TEMPERATURE
              value: "0.1"
      imagePullSecrets:
      - name: dockerhub
                    
---
kind: Service
apiVersion: v1
metadata:
  namespace: default
  name: chatbot-ui-staging
  labels:
    app: chatbot-ui-staging
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
  selector:
    app: chatbot-ui-staging
  type: ClusterIP
